version: "3"
services:
  engecopi:
    image: tomcat:8
    container_name: eng_agenda_recebimento
    ports:
      - "8021:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: /etc/ebean.properties
    volumes:
      - ./build/libs/agendaRecebimento-1.0.war:/usr/local/tomcat/webapps/agendaRecebimento.war
      - ./ebean.properties:/etc/ebean.properties
    restart: always
    networks:
      rede_agenda_recebimento:
        ipv4_address: 172.121.1.1
networks:
  rede_agenda_recebimento:
    ipam:
      driver: default
      config:
        - subnet: 172.121.0.0/16
